server:
  port: 8090

grpc:
  client:
    client-grpc-server:
      address: "localhost:8080"
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true

spring:
  data:
    redis:
      client-type: lettuce
      host: localhost
      port: 8007
